### ISSUE TITLE
When editing multiple files

### ISSUE THREAD

**Issue by JuarezASF** [jaxbot/semantic-highlight.vim#44]
How do you suggest to use the plugin for editing multiple files? I added autocmd bindings to re-run semantinc highlight every time I change buffer. I have this on my ftplugin/python.vim : 

   autocmd BufEnter *.py :SemanticHighlight
   autocmd BufEnter *.py :RebuildSemanticColors

As the multiple files start to get bigger and bigger, it gets slow to change buffers. Can we keep only one string -> color map for all opened buffers?

**Comment by faceleg** [comment]
See if these help:

```
let g:semanticUseCache = 1
let g:semanticPersistCache = 1

**Comment by faceleg** [comment]
Also I don't think you need to rebuild so often
