### ISSUE TITLE
GUI colors are can't be changed

### ISSUE THREAD

**Issue by hoschi** [jaxbot/semantic-highlight.vim#52]
Commit c76c35 changed the colors, but
`let s:semanticGUIColors = [ '#72d572', '#c5e1a5', '#e6ee9c', '#fff59d', '#ffe082', '#ffcc80', '#ffab91', '#bcaaa4', '#b0bec5', '#ffa726', '#ff8a65', '#f9bdbb', '#f9bdbb', '#f8bbd0', '#e1bee7', '#d1c4e9', '#ffe0b2', '#c5cae9', '#d0d9ff', '#b3e5fc', '#b2ebf2', '#b2dfdb', '#a3e9a4', '#dcedc8' , '#f0f4c3', '#ffb74d' ]`

nor
`let g:semanticGUIColors = [ '#72d572', '#c5e1a5', '#e6ee9c', '#fff59d', '#ffe082', '#ffcc80', '#ffab91', '#bcaaa4', '#b0bec5', '#ffa726', '#ff8a65', '#f9bdbb', '#f9bdbb', '#f8bbd0', '#e1bee7', '#d1c4e9', '#ffe0b2', '#c5cae9', '#d0d9ff', '#b3e5fc', '#b2ebf2', '#b2dfdb', '#a3e9a4', '#dcedc8' , '#f0f4c3', '#ffb74d' ]`

seem to change the default value :(

**Comment by faceleg** [comment]
Could you confirm this by supplying a list that contains only one colour?

**Comment by hoschi** [comment]
I can confirm, I tried already only two colors and the plugin uses still the default ones.

**Comment by faceleg** [comment]
Should be fixed, sorry about that!

**Comment by hoschi** [comment]
With 24 configured colors it works now.

With two colors on master (326b55) the colors don't cycle after two keywords anymore:
![2016-04-18-154535_593x779_scrot](https://cloud.githubusercontent.com/assets/163128/14606338/12803ac8-057d-11e6-8e9b-c8faa622e9f2.png)

config:
```
let g:semanticGUIColors = [ '#ffffff', '#000000']
```

**Comment by faceleg** [comment]
I always use a bunch of colours - if you would like to use this plugin with such a small handful of colours, we accept PRs!

**Comment by faceleg** [comment]
Also check if you're using the cache feature, if so try it with the cache off
