### ISSUE TITLE
How to get it highlight words in realtime?

### ISSUE THREAD

**Issue by liber145** [jaxbot/semantic-highlight.vim#73]
It is a great color highlighting plugin for python. I have been looking for such a plugin for some time. Now, I have one more problem. I need to turn off and on the `SemanticHighlightToggle` to highlight the added new words. How could I get it to work in real time?

**Comment by noboruma** [comment]
Not exactly real time, but you can use that trick:
`au BufWritePost <buffer> :SemanticHighlight`
This will apply the highlighting every-time you save your file.
